<?php

namespace AppBundle\Repository;

/**
 * IntraAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntraEventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByDatePublication()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:IntraEvents e ORDER BY e.newsDatePublication DESC'
            )
            ->getResult();
    }

}
