<?php

namespace AppBundle\Repository;

/**
 * IntraGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntraGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
