<?php

namespace AppBundle\Repository;

/**
 * IntraAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntraAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
