<?php

namespace AppBundle\Form;

use AppBundle\Entity\IntraDepartment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class addDepartment extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $array = $options['departmentDirectorUid'];
        $builder
            ->add('departmentName', TextType::class, array('label' => 'Nazwa '))
            ->add('save', SubmitType::class, array('label' => 'Dodaj'));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver
            ->setDefaults(array(
                'departmentDirectorUid' => null,
                'data_class' => IntraDepartment::class))
            ->setRequired('departmentDirectorUid')
            ->setAllowedTypes('departmentDirectorUid', array('array'));
    }

    public function getName()
    {
        return 'app_bundle_intra_department';
    }
}