<?php

namespace AppBundle\Form;

use AppBundle\Entity\IntraDivision;
use AppBundle\Entity\IntraDepartment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class editDivision extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('divisionName', TextType::class, array('label' => 'Nazwa '))
            ->add('save', SubmitType::class, array('label' => 'Zapisz'));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(array(
            'data_class' => IntraDivision::class,
        ));
    }

    public function getName()
    {
        return 'app_bundle_intra_division';
    }
}