<?php

namespace AppBundle\Form;

use AppBundle\Entity\IntraDivisionDepartmentLink;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class editDivisionDepartment extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $array = $options['departmentName'];
        $builder
            ->add('departmentName', ChoiceType::class, array(
                'choices' => array_flip($array),
                'label' => 'Departament',
                'choices_as_values' => true))
            ->add('save', SubmitType::class, array('label' => 'Zapisz'));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver
            ->setDefaults(array(
                'departmentName' => null,
                'data_class' => IntraDivisionDepartmentLink::class))
            ->setRequired('departmentName')
            ->setAllowedTypes('departmentName', array('array'));
    }

    public function getName()
    {
        return 'app_bundle_intra_division_department_link';
    }
}